apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-gateway-staging
  namespace: argocd
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Venkatraj1986/fintech-gitops_VR
    targetRevision: HEAD
    path: payment-gateway
    helm:
      valueFiles:
        - values/staging.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

